#!/usr/bin/env bash
# generate-codex-config.sh — print the Codex MCP server snippet (brief §21).
#
# This script only PRINTS. It never writes to ~/.codex/config.toml or any
# other file outside its own stdout. Applying the snippet is a manual step
# for the user (or Sol) — see the loud comment at the bottom of the output.
#
# tool_timeout_sec is derived from this project's OWN configured
# dispatcher.max_timeout_seconds plus a fixed safety margin, so Codex never
# times out an MCP call before the dispatcher's own process-group timeout
# would have already terminated the worker and returned a result.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd)"
VENV_PY="${PROJECT_ROOT}/.venv/bin/python"
ENTRYPOINT="${PROJECT_ROOT}/.venv/bin/sol-claude-dispatcher"

#: Safety margin added on top of the configured maximum worker timeout
#: (brief §21: "computed as config max_timeout_seconds + 300 margin").
MARGIN_SECONDS=300

CONFIG_PATH="${SOL_DISPATCHER_CONFIG:-${PROJECT_ROOT}/config/dispatcher.toml}"

max_timeout_seconds() {
    if [[ ! -x "$VENV_PY" ]]; then
        echo "3600"  # falls back to the example config's default (brief §35)
        return
    fi
    if [[ ! -f "$CONFIG_PATH" ]]; then
        echo "3600"
        return
    fi
    "$VENV_PY" -c "
from sol_claude_dispatcher.config import load_config
cfg = load_config('${CONFIG_PATH}')
print(cfg.dispatcher.max_timeout_seconds)
" 2>/dev/null || echo "3600"
}

MAX_TIMEOUT="$(max_timeout_seconds)"
TOOL_TIMEOUT_SEC=$((MAX_TIMEOUT + MARGIN_SECONDS))

cat <<EOF
# ============================================================================
# Generated by scripts/generate-codex-config.sh — DO NOT APPLY AUTOMATICALLY.
#
# This is a PRINT-ONLY script. Nothing on this host was modified by running
# it. To activate the dispatcher inside Codex, a human (or Sol, with the
# human's knowledge) must:
#
#   1. open ~/.codex/config.toml
#   2. back it up first (this script does not do that for you)
#   3. paste the [mcp_servers.sol_claude_dispatcher] block below into it,
#      preserving every other [mcp_servers.*] entry already present
#   4. save, and restart/reload Codex so it picks up the new MCP server
#
# tool_timeout_sec below = dispatcher.max_timeout_seconds (${MAX_TIMEOUT}s,
# read from ${CONFIG_PATH}$( [[ -f "$CONFIG_PATH" ]] || echo " — not found, used the shipped default" ))
# + a ${MARGIN_SECONDS}s safety margin, so Codex's own MCP tool-call timeout
# never fires before the dispatcher's process-group timeout would already
# have terminated the worker and returned a structured result.
# ============================================================================

[mcp_servers.sol_claude_dispatcher]
command = "${ENTRYPOINT}"
args = []
cwd = "${PROJECT_ROOT}"

startup_timeout_sec = 10
tool_timeout_sec = ${TOOL_TIMEOUT_SEC}
required = false

enabled_tools = [
  "dispatch_claude_task",
  "resume_claude_task",
  "review_task_with_fable",
  "get_task"
]

# ============================================================================
# Reminder: this snippet was PRINTED, not installed. ~/.codex/config.toml has
# not been touched. Apply it yourself when you are ready (step 5 of
# README.md's activation steps is intentionally manual).
# ============================================================================
EOF
